### ISSUE TITLE
Support pydantic v2

### ISSUE THREAD

**Issue by jmagnuson** [nf1s/fastapi-camelcase#20]
Pydanic [Model Config](https://docs.pydantic.dev/latest/usage/model_config/) docs describe the `Config` class (which `fastapi-camelcase` uses) as being deprecated. But it looks like the [alias generator](https://docs.pydantic.dev/latest/usage/model_config/#alias-generator) paradigm should be readily portable.

**Comment by ShaneZhengNZ** [comment]
I had huge issues today after we upgrade to pydantic v2 with this library. Eventually, I remove this library from my repo, just use the pydantic build-in alias generator to_camel.

Now, I think this library can be deprecated now.

**Comment by jmagnuson** [comment]
While abstracting the internals of pydantic is nice, I agree; it's pretty trivial to implement `CamelModel` without this library. For posterity:

```python
from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

class CamelModel(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True
    )
```

**Comment by nf1s** [comment]
Thank you very much @jmagnuson, it is fixed now
